argument_defaults = dict(
    dataroot='C:\\Users\Goko\Desktop\part1235',
    version='v1.0-trainval',
    filename='2d_annotations.json',
    export_path='F:/data/videos/',
    dataset_path='dataset_object.json',
    poc_mode='peak_number_both',
    video_data_path='C:/Users/Asli/Desktop/poc/dataset_{}.json',
    feature_path="../feature_extractor/output_average_101_peak_number_both.json",
    selected_scene="",
    colored_graph=True,
    extractor="F:/data/features",
    aggregation = "F:\\agg\\",
    output_path='F:/data/segmented_videos',
    plot_output = "F:\\{}",
    threads = [],
)